In [27]:
pd.set_option("display.max_columns", None)
pd.set_option('display.max_rows', 500)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge, Lasso, ElasticNet, LinearRegression
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
import sklearn.model_selection as ms
from sklearn import ensemble
from sklearn import metrics
from sklearn import tree
from sklearn.preprocessing import LabelEncoder
from sklearn import svm

In [2]:
df = pd.read_csv('Ames_Housing_Price_Data.csv')

In [6]:
df = df.fillna(0)
df

,Unnamed: 0,PID,GrLivArea,SalePrice,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,909176150,856,126000,30,RL,0.0,7890,Pave,0,...,166,0,0,0,0,0,3,2010,WD,Normal
1,2,905476230,1049,139500,120,RL,42.0,4235,Pave,0,...,0,0,0,0,0,0,2,2009,WD,Normal
2,3,911128020,1001,124900,30,C (all),60.0,6060,Pave,0,...,0,0,0,0,0,0,11,2007,WD,Normal
3,4,535377150,1039,114000,70,RL,80.0,8146,Pave,0,...,111,0,0,0,0,0,5,2009,WD,Normal
4,5,534177230,1665,227000,60,RL,70.0,8400,Pave,0,...,0,0,0,0,0,0,11,2009,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,759,903205040,952,121000,30,RL,0.0,8854,Pave,0,...,40,0,0,0,0,0,5,2009,WD,Normal
2576,760,905402060,1733,139600,20,RL,0.0,13680,Pave,0,...,0,0,0,0,0,0,6,2009,WD,Normal
2577,761,909275030,2002,145000,90,RH,82.0,6270,Pave,0,...,0,0,0,0,0,0,8,2007,WD,Normal
2578,762,907192040,1842,217500,60,RL,0.0,8826,Pave,0,...,0,0,0,0,0,0,7,2007,WD,Normal
2579,763,906223180,1911,215000,60,RL,80.0,9554,Pave,0,...,0,0,0,0,0,0,9,2006,WD,Normal

In [7]:
df.columns

Index(['Unnamed: 0', 'PID', 'GrLivArea', 'SalePrice', 'MSSubClass', 'MSZoning',
       'LotFrontage', 'LotArea', 'Street', 'Alley', 'LotShape', 'LandContour',
       'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1',
       'Condition2', 'BldgType', 'HouseStyle', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond',
       'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
       'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF',
       '2ndFlrSF', 'LowQualFinSF', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition'],
      dtype='object')

In [9]:
df = df.drop(columns = ['PID', 'Unnamed: 0'])
df

,GrLivArea,SalePrice,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,856,126000,30,RL,0.0,7890,Pave,0,Reg,Lvl,...,166,0,0,0,0,0,3,2010,WD,Normal
1,1049,139500,120,RL,42.0,4235,Pave,0,Reg,Lvl,...,0,0,0,0,0,0,2,2009,WD,Normal
2,1001,124900,30,C (all),60.0,6060,Pave,0,Reg,Lvl,...,0,0,0,0,0,0,11,2007,WD,Normal
3,1039,114000,70,RL,80.0,8146,Pave,0,Reg,Lvl,...,111,0,0,0,0,0,5,2009,WD,Normal
4,1665,227000,60,RL,70.0,8400,Pave,0,Reg,Lvl,...,0,0,0,0,0,0,11,2009,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,952,121000,30,RL,0.0,8854,Pave,0,Reg,Lvl,...,40,0,0,0,0,0,5,2009,WD,Normal
2576,1733,139600,20,RL,0.0,13680,Pave,0,IR1,Lvl,...,0,0,0,0,0,0,6,2009,WD,Normal
2577,2002,145000,90,RH,82.0,6270,Pave,0,Reg,HLS,...,0,0,0,0,0,0,8,2007,WD,Normal
2578,1842,217500,60,RL,0.0,8826,Pave,0,Reg,Lvl,...,0,0,0,0,0,0,7,2007,WD,Normal
2579,1911,215000,60,RL,80.0,9554,Pave,0,IR1,Lvl,...,0,0,0,0,0,0,9,2006,WD,Normal

In [13]:
X = df.drop(columns = 'SalePrice')
y = np.log10(df.SalePrice)

In [15]:
dummies = pd.get_dummies(X,drop_first=True)

In [16]:
dummies.shape

(2580, 269)

In [17]:
dummies

,GrLivArea,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_VWD,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,856,30,0.0,7890,6,6,1939,1950,0.0,238.0,...,0,0,0,0,1,0,0,0,1,0
1,1049,120,42.0,4235,5,5,1984,1984,149.0,552.0,...,0,0,0,0,1,0,0,0,1,0
2,1001,30,60.0,6060,5,9,1930,2007,0.0,737.0,...,0,0,0,0,1,0,0,0,1,0
3,1039,70,80.0,8146,4,8,1900,2003,0.0,0.0,...,0,0,0,0,1,0,0,0,1,0
4,1665,60,70.0,8400,8,6,2001,2001,0.0,643.0,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,952,30,0.0,8854,6,6,1916,1950,0.0,0.0,...,0,0,0,0,1,0,0,0,1,0
2576,1733,20,0.0,13680,3,5,1955,1955,0.0,0.0,...,0,0,0,0,1,0,0,0,1,0
2577,2002,90,82.0,6270,5,6,1949,1950,0.0,284.0,...,0,0,0,0,1,0,0,0,1,0
2578,1842,60,0.0,8826,7,5,2000,2000,144.0,841.0,...,0,0,0,0,1,0,0,0,1,0
2579,1911,60,80.0,9554,8,5,1993,1994,125.0,380.0,...,0,0,0,0,1,0,0,0,1,0

In [ ]:
df_float = X.select_dtypes(include='float')
df_float_to_int = df_float.astype(int)
df_numerical = X.select_dtypes(include='int64')
df_numerical = pd.concat([df_numerical,df_float_to_int],axis=1)
df_categorical = X.select_dtypes(include='object')

In [23]:
X.dtypes.value_counts(0)

object     43
int64      25
float64    11
dtype: int64

In [25]:
dummies.dtypes.value_counts()

uint8      233
int64       25
float64     11
dtype: int64

In [28]:
dummies.select_dtypes(include='int64')

,GrLivArea,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,LowQualFinSF,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,856,30,7890,6,6,1939,1950,856,0,0,1,0,2,1,4,1,0,0,0,0,166,0,0,3,2010
1,1049,120,4235,5,5,1984,1984,1049,0,0,2,0,2,1,5,0,0,105,0,0,0,0,0,2,2009
2,1001,30,6060,5,9,1930,2007,1001,0,0,1,0,2,1,5,0,154,0,42,86,0,0,0,11,2007
3,1039,70,8146,4,8,1900,2003,717,322,0,1,0,2,1,6,0,0,0,168,0,111,0,0,5,2009
4,1665,60,8400,8,6,2001,2001,810,855,0,2,1,3,1,6,0,0,45,0,0,0,0,0,11,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,952,30,8854,6,6,1916,1950,952,0,0,1,0,2,1,4,1,0,98,0,0,40,0,0,5,2009
2576,1733,20,13680,3,5,1955,1955,1733,0,0,2,0,4,1,8,1,0,0,0,0,0,0,0,6,2009
2577,2002,90,6270,5,6,1949,1950,1001,1001,0,2,0,4,2,8,0,0,0,0,0,0,0,0,8,2007
2578,1842,60,8826,7,5,2000,2000,985,857,0,2,1,3,1,7,1,193,96,0,0,0,0,0,7,2007
2579,1911,60,9554,8,5,1993,1994,1065,846,0,2,1,3,1,8,1,182,81,0,0,0,0,0,9,2006